# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "uniflight"
description = "Coalesces multiple ongoing tasks into a leader which does the work, and follower tasks that wait on the result, to prevent duplicate I/O or other downstream overhead."
version = "0.1.0"
readme = "README.md"
keywords = ["oxidizer", "coalescing", "stempede", "singleflight", "deduplication"]
categories = ["concurrency"]

edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
async-once-cell.workspace = true
dashmap.workspace = true
thread_aware.workspace = true

[dev-dependencies]
criterion = { workspace = true, features = ["async_tokio"] }
futures-util = { workspace = true, features = ["alloc", "std"] }
mutants.workspace = true
tick = { workspace = true, features = ["tokio"] }
tokio = { workspace = true, features = [
    "macros",
    "rt",
    "time",
    "rt-multi-thread",
] }

[lints]
workspace = true

[[bench]]
name = "performance"
harness = false

[[example]]
name = "cache_population"
