# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "fundle_macros_impl"
description = "Macros for the fundle crate."
version = "0.3.1"
readme = "README.md"
keywords = ["oxidizer", "di", "proc-macro"]
categories = ["rust-patterns"]

edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[package.metadata.cargo_check_external_types]
allowed_external_types = ["proc_macro2::*", "syn::error::*"]

[package.metadata.docs.rs]
all-features = true

[dependencies]
proc-macro2.workspace = true
quote.workspace = true
syn = { workspace = true, features = ["derive", "parsing", "proc-macro", "full", "extra-traits", "printing"] }

[dev-dependencies]
insta.workspace = true
mutants.workspace = true
prettyplease.workspace = true

[dev-dependencies.syn]
workspace = true
features = [
    "derive",
    "parsing",
    "proc-macro",
    "full",
    "extra-traits",
    "printing",
    "clone-impls",
]

[lints]
workspace = true
