# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "{{CRATE_NAME}}"
description = "{{CRATE_DESCRIPTION}}"
version = "0.1.0"
readme = "README.md"
keywords = ["oxidizer", {{CRATE_KEYWORDS}}]
categories = [{{CRATE_CATEGORIES}}]

edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository = "https://github.com/microsoft/oxidizer/tree/main/crates/{{CRATE_NAME}}"

[package.metadata.docs.rs]
all-features = true

[dependencies]

[dev-dependencies]

[lints]
workspace = true
