# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[licenses]
allow = [
    # You can add new entries to the list only from "Permissive OSS licenses" on this Microsoft-internal page: https://docs.opensource.microsoft.com/legal/resources/oss-licenses-by-type/.
    "MIT",
    "Apache-2.0",
    "ISC",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "Unicode-DFS-2016",
    "Unicode-3.0",
    "Zlib",
    "BSL-1.0",
]

confidence-threshold = 0.8
unused-allowed-license = "allow"
