[toolchain]
# This needs to match RUST_LATEST in constants.toml.
channel = "1.92"

# Additional targets to install for all builds (in both cloud and local builds).
# The toolchain will always come with support for the host platform.
targets = ["x86_64-pc-windows-msvc", "x86_64-unknown-linux-gnu"]
