# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

max_width = 140

# Above this line should be synchronized with rustfmt.toml

unstable_features = true

format_code_in_doc_comments = true
imports_granularity = "Module"
group_imports = "StdExternalCrate"
