# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "telemetry_events_macros"
description = "Macros for the telemetry_events crate."
version = "0.1.0"

edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository = "https://github.com/microsoft/oxidizer/tree/main/crates/telemetry_events_macros"

[package.metadata.docs.rs]
all-features = true

[lib]
proc-macro = true

[dependencies]
syn = { workspace = true, features = ["full", "derive", "printing", "parsing", "extra-traits", "proc-macro", "clone-impls"] }
telemetry_events_macros_impl.workspace = true

[dev-dependencies]
mutants.workspace = true

[lints]
workspace = true
