# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "fundle"
description = "Compile-time safe dependency injection for Rust."
version = "0.3.0"
readme = "README.md"
keywords = ["oxidizer", "di"]
categories = ["rust-patterns"]

edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository = "https://github.com/microsoft/oxidizer/tree/main/crates/fundle"

[package.metadata.cargo_check_external_types]
allowed_external_types = ["fundle_macros::*"]

[package.metadata.docs.rs]
all-features = true

[dependencies]
fundle_macros.workspace = true

[dev-dependencies]
trybuild.workspace = true

[lints]
workspace = true
