# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "testing_aids"
description = "Testing utilities."
version = "0.0.0"
readme = "README.md"
publish = false

edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
futures = { workspace = true, features = ["executor"] }
tracing = { workspace = true, features = ["std"] }
tracing-subscriber = { workspace = true, features = ["fmt"] }

[dev-dependencies]
mockall.workspace = true
mutants.workspace = true

[lints]
workspace = true
