# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "fundle_macros"
description = "Macros for the fundle crate."
version = "0.3.0"
readme = "README.md"
keywords = ["oxidizer", "di", "proc-macro"]
categories = ["rust-patterns"]

edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository = "https://github.com/microsoft/oxidizer/tree/main/crates/fundle_macros"

[package.metadata.docs.rs]
all-features = true

[lib]
proc-macro = true

[dependencies]
fundle_macros_impl.workspace = true

[dev-dependencies]
mutants.workspace = true

[lints]
workspace = true
